language: node_js
node_js:
  - lts/*
services:
  - docker

before_install:
  - docker build -t eshan25/examplereactapp -f Dockerfile .

script:
  - docker run eshan25/examplereactapp npm run test -- --coverage
  - echo "Hello World"
